version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: ["mvn", "spring-boot:run"]
    networks:
      - sigabem_ecosystem

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=sigabemdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sigabem_ecosystem

volumes:
  postgres_data:

networks:
  sigabem_ecosystem: